fn main() {
    tauri_build::build()
}
    //   set TAURI_SIGNING_PRIVATE_KEY=dW50cnVzdGVkIGNvbW1lbnQ6IHJzaWduIGVuY3J5cHRlZCBzZWNyZXQga2V5ClJXUlRZMEl5UnJFNnZIZWh0V1Q0OXBWK3Vhd2FBcndZZ1FMMm5GVUhSR1BHYTFYbjNZRUFBQkFBQUFBQUFBQUFBQUlBQUFBQTM5UG5wWjNpY1BpWURHUEhWeHBIU2FMWmV1UWFNV1ltYmtJVlY1R2RhSDkvNjNXUU9sUWdSRlcxbUU3dEtxUU1yV3FvZzYvQk93Q0NsbjQ2cERFNGQ5UnhiVFgybUYwNXZ5SzB1Z1pDdldzMHdkcklqVlJFT0cxWnBlcVUzanBWdmI4L0QrbDZFU1k9Cg==
    //   set TAURI_SIGNING_PRIVATE_KEY_PASSWORD=dangofugu
    //   set RUSTFLAGS=-C link-args=/STACK:33554432 && cargo run --release