import { useState, useCallback, useEffect } from 'react';
import { useToast } from "@/components/ui/use-toast"
import type { Task, Column as ColumnType } from "@/types/kanban"
import { invoke } from '@tauri-apps/api/core';

export const useTaskStore = () => {
  const [columns, setColumns] = useState<ColumnType[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const { toast } = useToast();

  const loadTasks = useCallback(async () => {
    try {
      setIsLoading(true);
      const tasks: Task[] = await invoke('get_all_tasks');
      
      // Group tasks by status
      const tasksByStatus = tasks.reduce((acc, task) => {
        if (!acc[task.status]) {
          acc[task.status] = [];
        }
        acc[task.status].push(task);
        return acc;
      }, {} as Record<string, Task[]>);

      // Create columns with tasks
      const defaultColumns = [
        { id: 'column-1', title: 'To Do', tasks: tasksByStatus['To Do'] || [], color: 'bg-blue-50 dark:bg-blue-900/30' },
        { id: 'column-2', title: 'In Progress', tasks: tasksByStatus['In Progress'] || [], color: 'bg-yellow-50 dark:bg-yellow-900/30' },
        { id: 'column-3', title: 'Blocked', tasks: tasksByStatus['Blocked'] || [], color: 'bg-red-50 dark:bg-red-900/30' },
        { id: 'column-4', title: 'Completed', tasks: tasksByStatus['Completed'] || [], color: 'bg-green-50 dark:bg-green-900/30' },
      ];

      setColumns(defaultColumns);
    } catch (error) {
      console.error('Failed to load tasks:', error);
      toast({
        title: 'Error',
        description: 'Failed to load tasks',
        variant: 'destructive',
      });
    } finally {
      setIsLoading(false);
    }
  }, [toast]);

  const createTask = useCallback(async (task: Omit<Task, 'id' | 'createdAt'>) => {
    try {
      const newTask = await invoke<Task>('create_task', {
        task: {
          ...task,
          id: '', // Will be generated by the backend
          createdAt: new Date().toISOString(),
        },
      });
      
      await loadTasks();
      return newTask;
    } catch (error) {
      console.error('Failed to create task:', error);
      toast({
        title: 'Error',
        description: 'Failed to create task',
        variant: 'destructive',
      });
      throw error;
    }
  }, [loadTasks, toast]);

  const updateTask = useCallback(async (task: Task) => {
    try {
      await invoke('update_task', {
        id: task.id,
        updates: {
          title: task.title,
          description: task.description,
          status: task.status,
          dueDate: task.dueDate,
          subtasks: task.subtasks,
          customFields: task.customFields,
        },
      });
      
      await loadTasks();
    } catch (error) {
      console.error('Failed to update task:', error);
      toast({
        title: 'Error',
        description: 'Failed to update task',
        variant: 'destructive',
      });
      throw error;
    }
  }, [loadTasks, toast]);

  const deleteTask = useCallback(async (taskId: string) => {
    try {
      await invoke('delete_task', { id: taskId });
      await loadTasks();
    } catch (error) {
      console.error('Failed to delete task:', error);
      toast({
        title: 'Error',
        description: 'Failed to delete task',
        variant: 'destructive',
      });
      throw error;
    }
  }, [loadTasks, toast]);

  const moveTask = useCallback(async (taskId: string, fromColumnId: string, toColumnId: string, toIndex: number) => {
    try {
      // Find the task to move
      const fromColumn = columns.find(col => col.id === fromColumnId);
      const task = fromColumn?.tasks.find(t => t.id === taskId);
      
      if (!task) {
        throw new Error('Task not found');
      }

      // Update task status based on the target column
      const toColumn = columns.find(col => col.id === toColumnId);
      if (!toColumn) {
        throw new Error('Target column not found');
      }

      const updatedTask = {
        ...task,
        status: toColumn.title,
      };

      await updateTask(updatedTask);
    } catch (error) {
      console.error('Failed to move task:', error);
      toast({
        title: 'Error',
        description: 'Failed to move task',
        variant: 'destructive',
      });
      throw error;
    }
  }, [columns, updateTask, toast]);

  // Load tasks on component mount
  useEffect(() => {
    loadTasks();
  }, [loadTasks]);

  return {
    columns,
    isLoading,
    createTask,
    updateTask,
    deleteTask,
    moveTask,
    loadTasks,
    setColumns,
  };
};

export default useTaskStore;
