// This file is @generated by prost-build.
/// RTC service RPC message container
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RtcRpc {
    /// message type
    #[prost(oneof = "rtc_rpc::Message", tags = "1, 2, 3, 4, 5, 6, 7")]
    pub message: ::core::option::Option<rtc_rpc::Message>,
}
/// Nested message and enum types in `RtcRpc`.
pub mod rtc_rpc {
    /// message type
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Message {
        /// rtc session request
        #[prost(message, tag = "1")]
        RtcSessionRequest(super::RtcSessionRequest),
        /// rtc session response for request
        #[prost(message, tag = "2")]
        RtcSessionResponse(super::RtcSessionResponse),
        /// rtc session management
        #[prost(message, tag = "3")]
        RtcSessionManagement(super::RtcSessionManagement),
        /// rtc outgoing
        #[prost(message, tag = "4")]
        RtcOutgoing(super::RtcOutgoing),
        /// rtc incoming
        #[prost(message, tag = "5")]
        RtcIncoming(super::RtcIncoming),
        /// rtc session list request
        #[prost(message, tag = "6")]
        RtcSessionListRequest(super::RtcSessionListRequest),
        /// rtc session list response
        #[prost(message, tag = "7")]
        RtcSessionListResponse(super::RtcSessionListResponse),
    }
}
/// rtc session request (caller initiates with SDP offer)
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RtcSessionRequest {
    /// group id (peer id of the callee)
    #[prost(bytes = "vec", tag = "1")]
    pub group_id: ::prost::alloc::vec::Vec<u8>,
    /// session type (1: audio, 2: video, 3: screen share)
    #[prost(uint32, tag = "2")]
    pub session_type: u32,
    /// SDP offer from caller (JSON serialized str0m SdpOffer)
    #[prost(string, tag = "3")]
    pub sdp_offer: ::prost::alloc::string::String,
}
/// rtc session response (includes SDP offer for callee to process)
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RtcSessionResponse {
    /// group id
    #[prost(bytes = "vec", tag = "1")]
    pub group_id: ::prost::alloc::vec::Vec<u8>,
    /// SDP offer received (callee needs this to generate answer)
    #[prost(string, tag = "2")]
    pub sdp_offer: ::prost::alloc::string::String,
}
/// rtc session management (callee accepts/denies with SDP answer)
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RtcSessionManagement {
    /// group id
    #[prost(bytes = "vec", tag = "1")]
    pub group_id: ::prost::alloc::vec::Vec<u8>,
    /// option (1: accept with SDP answer, 2: deny, 3: end)
    #[prost(uint32, tag = "2")]
    pub option: u32,
    /// SDP answer from callee (JSON serialized str0m SdpAnswer, only when option=1)
    #[prost(string, tag = "3")]
    pub sdp_answer: ::prost::alloc::string::String,
}
/// rtc outgoing
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RtcOutgoing {
    /// group id
    #[prost(bytes = "vec", tag = "1")]
    pub group_id: ::prost::alloc::vec::Vec<u8>,
    /// content
    #[prost(bytes = "vec", tag = "2")]
    pub content: ::prost::alloc::vec::Vec<u8>,
}
/// rtc incoming
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RtcIncoming {
    /// group id
    #[prost(bytes = "vec", tag = "1")]
    pub group_id: ::prost::alloc::vec::Vec<u8>,
    /// content
    #[prost(bytes = "vec", tag = "2")]
    pub content: ::prost::alloc::vec::Vec<u8>,
}
/// rtc sessions
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RtcSessionListRequest {}
/// rtc session
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RtcSession {
    /// group id
    #[prost(bytes = "vec", tag = "1")]
    pub group_id: ::prost::alloc::vec::Vec<u8>,
    /// session type
    #[prost(uint32, tag = "2")]
    pub session_type: u32,
    /// stste
    #[prost(uint32, tag = "3")]
    pub state: u32,
    /// created at
    #[prost(uint64, tag = "4")]
    pub created_at: u64,
    /// SDP offer
    #[prost(string, tag = "5")]
    pub sdp_offer: ::prost::alloc::string::String,
    /// SDP answer
    #[prost(string, tag = "6")]
    pub sdp_answer: ::prost::alloc::string::String,
}
/// rtc session list response
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RtcSessionListResponse {
    /// session list
    #[prost(message, repeated, tag = "1")]
    pub sessions: ::prost::alloc::vec::Vec<RtcSession>,
}
